config/routes.rb
Rails.application.routes.draw do
  get 'person/index'

  root 'welcome#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/person_controller.rb
class PersonController < ApplicationController
  def index
    @people = Person.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index 
        @teamName = "Axolotl"
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/person/index.html.erb
<h1>List of team members</h1>
<table>
    <tr><th>Name</th><th>Age</th></tr>
    <% @people.each do |person| %>
        <tr><td><%= person.name %></td><td><%= person.age %></td></tr>
    <% end %>
</table>

app/views/welcome/index.html.erb
<h1>TEAM <%= @teamName %></h1>
<p>See the team members <%= link_to "here", person_index_path %></p>